### PR TITLE
PR to fix #41

### LINKED ISSUE #41: Verify that getPaymentInfo/getPaymentMethods works for built-in __EXTERNAL_PAYMENT__ plugin
~~When asking for plugin specific information for external payments, the call will almost always fail since not all of the payments are kept in memory.~~

### PR DESCRIPTION
**Pull request by maguero**
Verify that getPaymentInfo/getPaymentMethods works for built-in __EXTERNAL_PAYMENT__ plugin

### CODE REVIEW

File: payment/src/test/java/org/killbill/billing/payment/api/TestExternalPaymentPlugin.java [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+public class TestExternalPaymentPlugin extends PaymentTestSuiteWithEmbeddedDB {
+
+    private ExternalPaymentProviderPlugin plugin;
+
+    final PaymentOptions INVOICE_PAYMENT = new PaymentOptions() {
+        @Override
+        public boolean isExternalPayment() {
+            return false;
+        }
+
```
Comment (sbrossie) [inline payment/src/test/java/org/killbill/billing/payment/api/TestExternalPaymentPlugin.java]: That does not seem to be used you can remove it.
