### PR TITLE
Fix for #1472

### LINKED ISSUE #1472: NPE in DefaultPaymentControlContext
Reported by @meden: https://groups.google.com/g/killbilling-users/c/X4qmOcclyLA/m/16AJ4QdBBAAJ

### PR DESCRIPTION
**Pull request by meden**
Changes the DefaultPaymentControlContext constructor signature to accept an account id instead
of a full account. This allows to build a CallContext even if the
account is null (e.g. when processing a PSP notification).

Fixes #1472

### CODE REVIEW

File: payment/src/main/java/org/killbill/billing/payment/core/sm/control/CompletionControlOperation.java [hunk 1]
```diff
@@ -107,13 +111,12 @@ public OperationResult doOperationCallback() throws OperationException {
                     } else {
                         throw new OperationException(null, executePluginOnFailureCallsAndSetRetryDate(updatedPaymentControlContext));
                     }
-                } catch (final PaymentApiException e) {
+                } catch (final PaymentApiException | RuntimeException e) {
```
Comment (pierre) [inline payment/src/main/java/org/killbill/billing/payment/core/sm/control/CompletionControlOperation.java:114]: We actually don't use Multi-Catch statements -- could you revert this?

File: payment/src/main/java/org/killbill/billing/payment/core/sm/control/OperationControlCallback.java [hunk 2]
```diff
@@ -145,10 +150,8 @@ public OperationResult doOperationCallback() throws OperationException {
                     } else {
                         throw new OperationException(null, executePluginOnFailureCallsAndSetRetryDate(updatedPaymentControlContext));
                     }
-                } catch (final PaymentApiException e) {
+                } catch (final PaymentApiException | RuntimeException e) {
```
Comment (pierre) [inline payment/src/main/java/org/killbill/billing/payment/core/sm/control/OperationControlCallback.java:153]: Same remark.

**Review by pierre — CHANGES_REQUESTED** [review]
Just one stylistic change, otherwise, assuming CI is ✅, :shipit: 

Thanks!

File: payment/src/main/java/org/killbill/billing/payment/core/sm/control/CompletionControlOperation.java (hunk 1 above)
Comment (meden) [reply payment/src/main/java/org/killbill/billing/payment/core/sm/control/CompletionControlOperation.java:114]: Yes of course... Sorry, Idea inspections :sweat_smile:
It is fine to add a commit here, or you prefer me to close this, force-push an amended commit, and make new PR?

Comment (meden) [reply payment/src/main/java/org/killbill/billing/payment/core/sm/control/CompletionControlOperation.java]: Nevermind, I force-pushed. I hope to not have break anything... :smile:

**Review by sbrossie — APPROVED** [review]

**Review by pierre — APPROVED** [review]

**Comment by pierre** [comment]
Thanks!
