### PR TITLE
Correct currency symbol for different Locale and Invoice Currency

### LINKED ISSUE #118: Invoice formatter display wrong currency symbol
First of all, the code is using the locale to set the currency formatter. For instance in 
DefaultInvoiceFormatter:

```
 public String getFormattedPaidAmount() {
        final NumberFormat number = NumberFormat.getCurrencyInstance(locale);
        return number.format(getPaidAmount().doubleValue());
 }
```

The number format returned is based on the locale which is 'good' so it knows how to display the dots, comma, ... but wrong it comes to display the currency symbol.

### PR DESCRIPTION
**Pull request by vp-maguero**
this fixed #118: Invoice formatter displays now correct currency symbol

### CODE REVIEW

File: invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java [hunk 1]
```diff
@@ -71,6 +72,18 @@
     private final InternalTenantContext context;
     private final ResourceBundleFactory bundleFactory;
 
+    public static Map<java.util.Currency, Locale> currencyLocaleMap;
```
Comment (pierre) [inline invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java]: Could you put this initialization in the constructor of `DefaultInvoiceFormatterFactory` (and change the `DefaultInvoiceFormatter` constructor to accept it as an argument)? `static` initialization makes me nervous...

Also, feel free to expose a package protect getter in `DefaultInvoiceFormatterFactory`, so it's easier to update tests (e.g. `TestDefaultInvoiceFormatter`).

File: invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java [hunk 2]
```diff
@@ -213,20 +226,35 @@ public BigDecimal getBalance() {
...
-        final NumberFormat number = NumberFormat.getCurrencyInstance(locale);
-        return number.format(getBalance().doubleValue());
+        return getFormattedAmountByLocaleAndInvoiceCurrency(getBalance());
+    }
+
+    /**
+     * Returns the amount with the correct currency symbol
+     *
+     * @param amount
+     * @return
```
Comment (pierre) [inline invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java]: Either document the fields or simply put a non-Javadoc comment, e.g.:

```
// Returns the amount with the correct currency symbol
```

Otherwise, the build will fail on Java 8 where doclint is [enabled by default](http://blog.joda.org/2014/02/turning-off-doclint-in-jdk-8-javadoc.html).

File: invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java [hunk 3]
```diff
@@ -187,6 +186,127 @@ public void testFormattedAmount() throws Exception {
     }
 
     @Test(groups = "fast")
+    public void testFormattedAmountFranceAndJPY() throws Exception {
+
+        final FixedPriceInvoiceItem fixedItem = new FixedPriceInvoiceItem(UUID.randomUUID(), UUID.randomUUID(), null, null,
+                                                                             UUID.randomUUID().toString(), UUID.randomUUID().toString(),
+                                                                             new LocalDate(), new BigDecimal("1500.00"), Currency.JPY);
+        final Invoice invoiceEUR = new DefaultInvoice(UUID.randomUUID(), new LocalDate(), new LocalDate(), Currency.JPY);
```
Comment (pierre) [inline invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java]: Rename to `invoiceJPY`, a bit confusing otherwise :smile_cat:

File: invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java [hunk 4]
```diff
@@ -187,6 +186,127 @@ public void testFormattedAmount() throws Exception {
...
+                    "</tr>",
+                    Locale.US);
+    }
+
+    @Test(groups = "fast")
+    public void testFormattedAmountUSAndGBP() throws Exception {
+        final FixedPriceInvoiceItem fixedItemEUR = new FixedPriceInvoiceItem(UUID.randomUUID(), UUID.randomUUID(), null, null,
+                                                                             UUID.randomUUID().toString(), UUID.randomUUID().toString(),
+                                                                             new LocalDate(), new BigDecimal("1499.95"), Currency.GBP);
+        final Invoice invoiceEUR = new DefaultInvoice(UUID.randomUUID(), new LocalDate(), new LocalDate(), Currency.GBP);
```
Comment (pierre) [inline invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java]: `invoiceGBP`.

File: invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java [hunk 5]
```diff
@@ -213,20 +226,35 @@ public BigDecimal getBalance() {
...
+     */
+    private String getFormattedAmountByLocaleAndInvoiceCurrency(BigDecimal amount) {
+        final DecimalFormat number = (DecimalFormat) DecimalFormat.getCurrencyInstance(locale);
```
Comment (pierre) [inline invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java]: Maybe rename it to `numberFormatter`?

File: invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java [hunk 6]
```diff
@@ -187,6 +186,127 @@ public void testFormattedAmount() throws Exception {
...
+                    "    <td class=\"amount\"><strong>{{invoice.formattedChargedAmount}}</strong></td>\n" +
+                    "</tr>\n" +
+                    "<tr>\n" +
+                    "    <td class=\"amount\"><strong>{{invoice.formattedPaidAmount}}</strong></td>\n" +
+                    "</tr>\n" +
+                    "<tr>\n" +
+                    "    <td class=\"amount\"><strong>{{invoice.formattedBalance}}</strong></td>\n" +
+                    "</tr>",
+                    "<tr>\n" +
+                    "    <td class=\"amount\"><strong>1 500,00 ￥</strong></td>\n" +
```
Comment (pierre) [inline invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java]: I'm not an expert but intuitively this seems wrong, as the Yen doesn't have cents. I believe you need to set in `getFormattedAmountByLocaleAndInvoiceCurrency`:

```
numberFormatter.setMaximumFractionDigits(currency.getDefaultFractionDigits());
```

To verify, could you add a test with the BTC currency, and verify we can display more than 2 digits (e.g. `105.28843439` is valid and probably shouldn't be rounded even with a French locale)?

File: invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java (hunk 1 above)
Comment (vp-maguero) [inline invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java]: No problem, I'll move it. Not sure what do you mean with add it to the constructor parameters because this method takes possible values from Locale.getAvailableLocales().

Comment (pierre) [inline invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java]: What I meant was that if `currencyLocaleMap ` becomes an instance variable of `DefaultInvoiceFormatterFactory`, you'll need to change the constructor of `DefaultInvoiceFormatter` to pass it as an argument (so it's available in `DefaultInvoiceFormatter`).

`DefaultInvoiceFormatterFactory` however should still have a no-argument constructor.

File: invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java (hunk 6 above)
Comment (vp-maguero) [inline invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java]: 1 - FractionDigits fixed.

2 - Running into an issue when try to create an instance of "BTC" java.util.Currency. This is not contains in java.util.Currency.getAvailableCurrencies()

Related [link] (http://stackoverflow.com/questions/20474336/implementing-bitcoin-and-java-util-currency).

Do you consider to refactor the code to have it working? or do you want to set a default ***currency*** for all not know currency codes?

Comment (pierre) [inline invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java]: > Running into an issue when try to create an instance of "BTC" java.util.Currency. This is not contains in java.util.Currency.getAvailableCurrencies()

Ah, interesting! For the test, let's use the Omani Rial instead (`OMR`), which has 3 decimal places.

> Do you consider to refactor the code to have it working? or do you want to set a default currency for all not know currency codes?

Thinking about it, we actually already use [Joda-Money](http://www.joda.org/joda-money/) in Kill Bill to handle such currencies. Could we refactor `getFormattedAmountByLocaleAndInvoiceCurrency` to simply use [MoneyFormatterBuilder](http://www.joda.org/joda-money/userguide.html) instead of `DecimalFormat` directly (it looks like it uses [DecimalFormat](https://github.com/JodaOrg/joda-money/blob/e8c83944f5d6407007d41de2fa89d79ab68f18af/src/main/java/org/joda/money/format/MoneyAmountStyle.java#L272) behind the scenes)?

Comment (vp-maguero) [inline invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java]: I was able to fix "BTC" currency and get more than 2 decimals depending on the currency format.

Another issue is that [DefaultAmountFormatter] (https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/DefaultAmountFormatter.java#L23) is always [rounding] (https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java#L201) with scale = 2. 

Input:
```
new BigDecimal("1105.28843439")
```
Then:
```
BTC1,105.29000000
```

File: invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java (hunk 1 above)
Comment (vp-maguero) [inline invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java]: got it.

File: invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java (hunk 6 above)
Comment (pierre) [inline invoice/src/test/java/org/killbill/billing/invoice/template/formatters/TestDefaultInvoiceFormatter.java]: > Another issue is that [DefaultAmountFormatter] (https://github.com/killbill/killbill/blob/master/util/src/main/java/org/killbill/billing/util/DefaultAmountFormatter.java#L23) is always [rounding] (https://github.com/killbill/killbill/blob/master/invoice/src/main/java/org/killbill/billing/invoice/template/formatters/DefaultInvoiceFormatter.java#L201) with scale = 2.

Weird, I cannot think of the reason why we forced that rounding (introduced by https://github.com/killbill/killbill/commit/0cab890a68df0b19c01886f2885ca9695d70600a). Maybe before we didn't enforce a default locale (https://github.com/killbill/killbill/commit/abed7b57fbdb6c2eef4bc188d50820a325b51f51)?

I would remove the rounding and verify other tests still pass.

**Comment by vp-maguero** [comment]
Comments are fixed by last commit 43afb0759795e3ffdf748925e592b65738e00f25

**Comment by pierre** [comment]
Thanks!

FYI, I've made a few small fixes:

* [trivial reformatting](https://github.com/killbill/killbill/commit/896ec16586e33e5867bbba8eaa21392042704149)
* [share the currency -> locale map in tests](https://github.com/killbill/killbill/commit/8ea9e88c4d4b6818801e07295315f2d6777cf286)
* [reduce catch block](https://github.com/killbill/killbill/commit/abe94d64e4f6a833e179519f0ea621dcc0d9f84b)
* [remove third digit](https://github.com/killbill/killbill/commit/fbf57b8265bc2cb143d46061988bf6c990aa5116) in euro test (only 2 digits is supported in practice for cents) and added the [OMR](https://github.com/killbill/killbill/commit/5927458b3546d6e0a2cdb6574ce58d318d0e1b7b) test
